all:
	i686-w64-mingw32-g++ revshell.cpp -o revshell.exe -lws2_32 -s -ffunction-sections -fdata-sections -Wno-write-strings -fno-exceptions -fmerge-all-constants -static-libstdc++ -static-libgcc
clean:
	rm -f revshell.exe
